experiment_name: "./2d_encoder/L2"
device: "cuda:0"  # run this on a gpu for a reasonable training time
bottleneck: 512
cat: 13
batch_size: 64
loss_criterion: "L2"
final_layer: "normal"
3d_autoencoder_path: "./3d_autoencoder/model_autoencoder_final.pth"
resume_ckpt: null
lr: 5e-5
max_epochs: 30
save_every_n: 1
validate_every_n: 3
autoencoder_bottleneck: 512
autoencoder_hidden_size: 256
autoencoder_output_size: 6144